name: Bump Version in README

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Get current version
      id: get_version
      run: |
        echo "VERSION=$(python -c 'from undetected_geckodriver import __version__; print(__version__)')" >> $GITHUB_ENV
    - name: Update README.md
      run: |
        sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/v${{ env.VERSION }}/g" README.md
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "chore: bump version in README.md to v${{ env.VERSION }}"
        git push
