name: Bump Version in README

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install package
      run: |
        python -m pip install --upgrade pip
    - name: Update README.md and commit changes
      run: |
        export VERSION=$(python -c 'from undetected_geckodriver import __version__; print(__version__)')
        sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/v${VERSION}/" README.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "chore: bump version in README.md to v${VERSION}"
        git push
